apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-fss-gateway
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  ingresses:
    - https://pensjon-selvbetjening-fss-gateway.dev.intern.nav.no
    - https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
  liveness:
    path: "/internal/liveness"
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: "/internal/readiness"
    periodSeconds: 30
  env:
    - name: ESB_URL
      value: https://tjenestebuss-q2.adeo.no
    - name: JOURNALFORING_URL
      value: https://dokarkiv-q2.dev.intern.nav.no/rest/journalpostapi/v1/journalpost
    - name: PEN_URL
      value: https://pensjon-pen-q2.dev.adeo.no/pen
    - name: STS_URL
      value: http://security-token-service.default.svc.nais.local/rest/v1/sts/token
    - name: FSSGW_LOGGING_LEVEL
      value: debug
  prometheus:
    enabled: true
    path: /internal/prometheus
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  webproxy: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-selvbetjening-opptjening-backend
          namespace: pensjonselvbetjening
          cluster: dev-fss
        - application: pensjon-selvbetjening-soknad-alder-backend
          namespace: pensjonselvbetjening
          cluster: dev-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvpensjon
        mountPath: /secrets/serviceuser
