apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-fss-gateway-{{ environment }}
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 5m
      memory: 384Mi
  ingresses:
    - https://pensjon-selvbetjening-fss-gateway-{{ environment }}.intern.dev.nav.no
    - https://pensjon-selvbetjening-fss-gateway-{{ environment }}.dev-fss-pub.nais.io
  port: 8080
  liveness:
    path: /internal/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  env:
    - name: ESB_URL
      value: https://tjenestebuss-{{ environment }}.adeo.no
    - name: PEP_GW_URL
      value: https://pep-gw-q1.oera-q.local:9443
    - name: POPP_URL
      value: https://pensjon-popp-{{ environment }}.dev.intern.nav.no
    - name: SPK_URL
      value: https://api.preprod.spk.no
    - name: SPORINGSLOGG_URL
      value: https://sporingslogg-q2.dev.intern.nav.no # only in q2
    - name: STS_URL
      value: http://security-token-service.aura.svc.nais.local
    - name: TP_URL
      value: https://tp-{{ environment }}.dev.intern.nav.no
    - name: WASAPP_URL
      value: https://wasapp-{{ environment }}.adeo.no
    - name: FSSGW_LOGGING_LEVEL
      value: debug
    - name: STDOUT_LOG_OUTPUT
      value: JSON
  envFrom:
    - secret: pensjon-selvbetjening-fss-gateway-srvpselv
    - secret: pensjon-selvbetjening-fss-gateway-srvpensjon
    - secret: pensjon-selvbetjening-fss-gateway-srvtjenestepensjon-simulering
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
  webproxy: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "spk:nav"
  accessPolicy:
    inbound:
      rules:
        - application: pensjonssimulator-q1
          namespace: pensjonskalkulator
          cluster: dev-gcp
        - application: pensjon-selvbetjening-opptjening-backend
          namespace: pensjonselvbetjening
          cluster: dev-gcp
        - application: pensjon-selvbetjening-soknad-alder-backend
          namespace: pensjonselvbetjening
          cluster: dev-gcp
        - application: pensjon-selvbetjening-soknad-alder-backend-ekstern
          namespace: pensjonselvbetjening
          cluster: dev-gcp
        - application: pensjon-pselv-{{ environment }}
          namespace: teampensjon
          cluster: dev-gcp
        - application: pensjon-pselv-q2
          namespace: teampensjon
          cluster: dev-fss
        - application: tjenestepensjon-simulering
          namespace: pensjonskalkulator
          cluster: dev-gcp
    outbound:
      external:
        - host: api.preprod.spk.no
        - host: pep-gw-q1.oera-q.local
          ports:
            - port: 9443
