apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-fss-gateway
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 1Gi
  ingresses:
    - https://pensjon-selvbetjening-fss-gateway.intern.nav.no
    - https://pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
  port: 8080
  liveness:
    path: /internal/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  env:
    - name: ESB_URL
      value: https://tjenestebuss.adeo.no
    - name: NORG2_URL
      value: https://app.adeo.no
    - name: OPPGAVE_URL
      value: https://oppgave.nais.adeo.no
    - name: PEN_URL
      value: https://pensjon-pen.nais.adeo.no
    - name: PENSJON_FULLMAKT_URL
      value: https://pensjon-representasjon.intern.nav.no
    - name: PENSJONREGLER_URL
      value: https://pensjon-regler.intern.nav.no
    - name: PEP_GW_URL
      value: https://pep-gw.oera.no:9443
    - name: POPP_URL
      value: https://pensjon-popp.nais.adeo.no
    - name: PREG_URL
      value: https://pensjon-preg.nais.adeo.no
    - name: SPK_URL
      value: https://api.prod.spk.no
    - name: SPORINGSLOGG_URL
      value: https://pensjon-sporingslogg-integrasjon.intern.nav.no
    - name: STS_URL
      value: http://security-token-service.aura.svc.nais.local
    - name: TP_URL
      value: https://tp.nais.adeo.no
    - name: WASAPP_URL
      value: https://wasapp.adeo.no
    - name: FSSGW_LOGGING_LEVEL
      value: info
    - name: STDOUT_LOG_OUTPUT
      value: JSON
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
  webproxy: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "spk:nav"
  accessPolicy:
    inbound:
      rules:
        - application: pensjonskalkulator-backend
          namespace: pensjonskalkulator
          cluster: prod-gcp
        - application: pensjonssimulator
          namespace: pensjonskalkulator
          cluster: prod-gcp
        - application: pensjon-selvbetjening-opptjening-backend
          namespace: pensjonselvbetjening
          cluster: prod-gcp
        - application: pensjon-selvbetjening-soknad-alder-backend
          namespace: pensjonselvbetjening
          cluster: prod-gcp
        - application: pensjon-pselv
          namespace: pensjondeployer
          cluster: prod-gcp
        - application: tjenestepensjon-simulering
          namespace: pensjonskalkulator
          cluster: prod-gcp
    outbound:
      external:
        - host: api.prod.spk.no
        - host: pep-gw.oera.no
          ports:
            - port: 9443
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvpselv
        mountPath: /secrets/serviceuser
      - kvPath: /serviceuser/data/prod/srvpensjon
        mountPath: /secrets/serviceuser2
      - kvPath: /serviceuser/data/prod/srvtjenestepensjon-simulering
        mountPath: /secrets/serviceuser3
